spring.datasource.url=${LOCAL_URL}
spring.datasource.username=${LOCAL_USER}
spring.datasource.password=${LOCAL_PASSWORD}
spring.datasource.DriverClassName=org.postgresql.Driver
spring.application.name=DND-Encounter-Tool
